<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Exception trong Rails - The more your try, the more your learn</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<meta name="author" content="Duy Chinh" /><meta name="description" content="Đặt vấn đề Tôi có một số tình huống diễn ra hàng ngày về con mèo của tôi. Nếu nó đói tôi cho nó ăn, nếu nó đi vs lung tung tôi sẽ dọn dẹp chúng.
Nhưng bỗng một ngày con mèo stupid của tôi bị &amp;ldquo;người ngoài hành tinh bắt cóc&amp;rdquo;, wtf?. Đây là một tình huống không bình thường và tôi không có một HÀNH ĐỘNG THỐNG NHẤT nào để đối phó với 1 tình huống như vậy, tôi có thể khóc, có thể báo công an, nhưng chắc chắn không thể có một cách giải quyết triệt để." /><meta name="keywords" content="ruby, rails, lap trinh, lam web, bao mat, hoc javascript, docker, postgresql, mysql" />






<meta name="generator" content="Hugo 0.55.6 with even 4.0.0" />


<link rel="canonical" href="https://1312047.github.io/post/2019-06-10-xu-ly-ngoai-le-trong-rails/" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">


<link href="/dist/even.c2a46f00.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">


<meta property="og:title" content="Exception trong Rails" />
<meta property="og:description" content="Đặt vấn đề Tôi có một số tình huống diễn ra hàng ngày về con mèo của tôi. Nếu nó đói tôi cho nó ăn, nếu nó đi vs lung tung tôi sẽ dọn dẹp chúng.
Nhưng bỗng một ngày con mèo stupid của tôi bị &ldquo;người ngoài hành tinh bắt cóc&rdquo;, wtf?. Đây là một tình huống không bình thường và tôi không có một HÀNH ĐỘNG THỐNG NHẤT nào để đối phó với 1 tình huống như vậy, tôi có thể khóc, có thể báo công an, nhưng chắc chắn không thể có một cách giải quyết triệt để." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://1312047.github.io/post/2019-06-10-xu-ly-ngoai-le-trong-rails/" />
<meta property="article:published_time" content="2019-06-10T00:00:00&#43;00:00"/>
<meta property="article:modified_time" content="2019-06-10T00:00:00&#43;00:00"/>

<meta itemprop="name" content="Exception trong Rails">
<meta itemprop="description" content="Đặt vấn đề Tôi có một số tình huống diễn ra hàng ngày về con mèo của tôi. Nếu nó đói tôi cho nó ăn, nếu nó đi vs lung tung tôi sẽ dọn dẹp chúng.
Nhưng bỗng một ngày con mèo stupid của tôi bị &ldquo;người ngoài hành tinh bắt cóc&rdquo;, wtf?. Đây là một tình huống không bình thường và tôi không có một HÀNH ĐỘNG THỐNG NHẤT nào để đối phó với 1 tình huống như vậy, tôi có thể khóc, có thể báo công an, nhưng chắc chắn không thể có một cách giải quyết triệt để.">


<meta itemprop="datePublished" content="2019-06-10T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2019-06-10T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="998">



<meta itemprop="keywords" content="rails,ruby," />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Exception trong Rails"/>
<meta name="twitter:description" content="Đặt vấn đề Tôi có một số tình huống diễn ra hàng ngày về con mèo của tôi. Nếu nó đói tôi cho nó ăn, nếu nó đi vs lung tung tôi sẽ dọn dẹp chúng.
Nhưng bỗng một ngày con mèo stupid của tôi bị &ldquo;người ngoài hành tinh bắt cóc&rdquo;, wtf?. Đây là một tình huống không bình thường và tôi không có một HÀNH ĐỘNG THỐNG NHẤT nào để đối phó với 1 tình huống như vậy, tôi có thể khóc, có thể báo công an, nhưng chắc chắn không thể có một cách giải quyết triệt để."/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">Chinh&#39;s notes</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a>
  </ul>
</nav>
  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">Chinh&#39;s notes</a>
</div>

<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li>
  </ul>
</nav>
    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Exception trong Rails</h1>

      <div class="post-meta">
        <span class="post-time"> 2019-06-10 </span>
        
          <span class="more-meta"> 998 words </span>
          <span class="more-meta"> 5 mins read </span>
        
      </div>
    </header>

    <div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  <div class="post-toc-content always-active">
    <nav id="TableOfContents">
<ul>
<li>
<ul>
<li><a href="#đặt-vấn-đề">Đặt vấn đề</a></li>
<li><a href="#luận-bàn">Luận bàn</a>
<ul>
<li><a href="#1-tìm-hiểu-về-exception">1. Tìm hiểu về Exception</a></li>
<li><a href="#2-làm-sao-để-lấy-về-đối-tượng-exception">2. Làm sao để lấy về đối tượng Exception</a></li>
<li><a href="#3-xây-dựng-một-class-exception">3. Xây dựng một class Exception</a></li>
<li><a href="#4-các-lớp-exception-có-sẵn-trong-ruby">4. Các lớp Exception có sẵn trong Ruby</a></li>
<li><a href="#5-cách-bắt-exception-hợp-lý">5. Cách bắt Exception hợp lý</a></li>
</ul></li>
<li><a href="#kết-luận">Kết luận</a></li>
</ul></li>
</ul>
</nav>
  </div>
</div>
    <div class="post-content">
      

<h2 id="đặt-vấn-đề">Đặt vấn đề</h2>

<p>Tôi có một số tình huống diễn ra hàng ngày về con mèo của tôi. Nếu nó đói tôi cho nó ăn, nếu nó đi vs lung tung tôi sẽ dọn dẹp chúng.</p>

<p>Nhưng bỗng một ngày con mèo stupid của tôi bị &ldquo;người ngoài hành tinh bắt cóc&rdquo;, wtf?. Đây là một tình huống không bình thường và tôi không có một <code>HÀNH ĐỘNG THỐNG NHẤT</code> nào để đối phó với 1 tình huống như vậy, tôi có thể khóc, có thể báo công an, nhưng chắc chắn không thể có một cách giải quyết triệt để. Trong lập trình ta gọi những tình huống mà logic luận lý sai lệch không còn đi theo logic bình thường như này là một exception.</p>

<p>Ví dụ như máy tính của bạn không được thiết kế để thực hiện phép chia cho số 0. Vậy khi bạn bắt nó thực hiện phép chia cho số 0, nó sẽ nghĩ &ldquo;wtf is going on?&rdquo; và đành quăng ra cho bạn một thông báo về việc bạn đã bắt nó làm một việc mà nó không được thiết kế để làm.</p>

<p>Trong bài viết này chúng ta sẽ tìm hiểu về exception trong ruby.</p>

<h2 id="luận-bàn">Luận bàn</h2>

<h3 id="1-tìm-hiểu-về-exception">1. Tìm hiểu về Exception</h3>

<p>Đầu tiên chúng ta phải ghi nhớ rằng khi một exception được gọi, chương trình của bạn sẽ ngừng và đoạn code phía sau không thể chạy được nữa.</p>

<ol>
<li><p>Tôi đến trường đón con mèo.</p></li>

<li><p>Tôi đem con mèo đi bán vào quán tiểu hổ.</p></li>
</ol>

<p>Nếu ở <code>bước 1</code>, thay vì đón thành công con mèo, tôi lại dính một exception &ldquo;MeoMissing&rdquo; vì lý do nó bị người ngoài hành tinh bắt cóc.</p>

<p>Khi này dĩ nhiên chương trình sẽ dừng lại, vì tôi làm gì còn con mèo để mà đem nó đi bán ở  <code>bước 2</code>.</p>

<p>Quay về với ví dụ đơn giản là chia cho số 0:</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span><span class="lnt">2
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="mi">10</span><span class="o">/</span><span class="mi">0</span>
<span class="c1"># =&gt; ZeroDivisionError (divided by 0)</span></code></pre></td></tr></table>
</div>
</div>
<p><code>ZeroDivisionError</code> là một exception được ruby tạo ra để trả về khi bạn cố chia một số cho số 0.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span></pre></td>
<td class="lntd">
<pre class="chroma">  if (chia đàng hoàng)
    thực hiện phép tính.
  else 
    if (chia cho số 0)
      trả về exception ZeroDivisionError 
    end
  end</pre></td></tr></table>
</div>
</div>
<p>Flow logic đơn giản về exception như trên.</p>

<h3 id="2-làm-sao-để-lấy-về-đối-tượng-exception">2. Làm sao để lấy về đối tượng Exception</h3>

<p>Như chúng ta đã biết, gần như mọi thứ trong ruby đều là object(Ngoại trừ method và block). Vậy nên Exception cũng là một đối tượng.</p>

<p>ZeroDivisionError ở trên là một Class, vậy khi bạn thực hiện một phép chia cho số 0, bạn đã rơi vào trường hợp mà ZeroDivisionError quản lý và nó sẽ trả về một đối tượng ZeroDivisionError.</p>

<p>Vậy tức là ở 2 lần chia cho số 0 khác nhau, nó sẽ trả về cho bạn 2 object exception khác nhau chỉ là cùng một class ZeroDivisionError.</p>

<p>Vậy cách nào để bắt được đối tượng này? Cú pháp để thực hiện việc này sẽ như sau:</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span><span class="lnt">6
</span><span class="lnt">7
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">begin</span>
  <span class="n">meo</span> <span class="o">=</span> <span class="mi">10</span>
  <span class="n">meo</span><span class="sr">/0
</span><span class="sr">rescue ZeroDivisionError =&gt; e
</span><span class="sr">  puts &#34;Exception Class: </span><span class="si">#{</span> <span class="n">e</span><span class="o">.</span><span class="n">class</span><span class="o">.</span><span class="n">name</span> <span class="si">}</span><span class="sr">&#34;
</span><span class="sr">  puts &#34;Exception Message: </span><span class="si">#{</span> <span class="n">e</span><span class="o">.</span><span class="n">message</span> <span class="si">}</span><span class="sr">&#34;
</span><span class="sr">end</span></code></pre></td></tr></table>
</div>
</div>
<p><code>rescue</code> là từ khoá sẽ giúp bạn lấy được đối tượng exception trả về. Như ví dụ trên tôi lấy đối tượng exeption trả về (nếu exception đó là dạng ZeroDivisionError) và truyền nó vào biến <code>e</code>. Từ đây <code>e</code> chính là object exception nếu exception đó xảy ra.</p>

<p>Tôi có thể dùng e để xuất ra các thông tin mà tôi cần như class name hay message thông báo lỗi.</p>

<h3 id="3-xây-dựng-một-class-exception">3. Xây dựng một class Exception</h3>

<p>Một sự thật hiển nhiên là những thiết kế có sẵn không bao giờ có thể cover cho tất cả các trường hợp có thể xảy ra trong thực tiễn. Đôi lúc bạn muốn thêm một exception để cover cho trường hợp của riêng dự án của bạn thì sao?</p>

<p>Câu trả lời mà tôi mới tìm được khá thú vị và cũng rất quen thuộc. Đó là Exception cũng có thể được tạo ra như một class bình thường. Hãy để nó kế thừa lớp <code>StandardError</code> là được.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">class</span> <span class="nc">MeoException</span> <span class="o">&lt;</span> <span class="no">StandardError</span><span class="p">;</span> <span class="k">end</span></code></pre></td></tr></table>
</div>
</div>
<p>Vậy là ta đã có một class exception của riêng mình. Khi cần gọi đến exception này thì ta sẽ gọi sử dụng phương thức <code>raise</code> để gọi một đối tượng.</p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">raise</span> <span class="no">MeoException</span><span class="o">.</span><span class="n">new</span><span class="p">(</span><span class="n">params_gi_do_ma_ban_muon</span><span class="p">)</span></code></pre></td></tr></table>
</div>
</div>
<p>Vậy trong class class <code>MeoException</code> ta sẽ thiết kế những gì? 😄 Tôi cũng chưa tìm hiểu.</p>

<h3 id="4-các-lớp-exception-có-sẵn-trong-ruby">4. Các lớp Exception có sẵn trong Ruby</h3>

<p><img src="/images/ruby-exception.jpg" alt="hoa" /></p>

<p>Đây là sơ đồ về các lớp exception trong ruby, nếu ta rescue một exception X, X lại có dăm 3 exception con, thì chỉ cần chương trình của bạn phát sinh vấn đề và trả ra một exception con nào đó thì X được gọi.</p>

<h3 id="5-cách-bắt-exception-hợp-lý">5. Cách bắt Exception hợp lý</h3>

<p><strong>Cách 1:</strong></p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">begin</span>
  <span class="n">di_don_con_meo_truong</span><span class="p">()</span>
<span class="k">rescue</span> <span class="no">Exception</span> <span class="o">=&gt;</span> <span class="n">e</span>
  <span class="c1"># do something</span>
<span class="k">end</span></code></pre></td></tr></table>
</div>
</div>
<p>Đây là một cách tệ vì khi rescue với Exception, lớp cha của tất cả các Exception khác thì nó cover quá nhiều trường hợp cũng trả ra exception, hãy nhớ lại ở trên chúng ta đã nói một khi Exception được trả về thì chương trình của bạn sẽ dừng lại. Vậy nên không sử dụng cách này.</p>

<p><strong>Cách 2:</strong></p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">begin</span>
  <span class="n">di_don_con_meo_truong</span><span class="p">()</span>
<span class="k">rescue</span> <span class="no">StandardError</span> <span class="o">=&gt;</span> <span class="n">e</span>
  <span class="c1"># do something</span>
<span class="k">end</span></code></pre></td></tr></table>
</div>
</div>
<p>Đây là cách làm tốt hơn, vì ta chỉ cover các lỗi standard, ít ra chương trình của bạn sẽ không thi thoảng bị shutdown mà không biết vì sao như cách đầu tiên.</p>

<p><strong>Cách 3:</strong></p>
<div class="highlight"><div class="chroma">
<table class="lntable"><tr><td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span><span class="lnt">5
</span></code></pre></td>
<td class="lntd">
<pre class="chroma"><code class="language-ruby" data-lang="ruby"><span class="k">begin</span>
  <span class="n">di_don_con_meo_truong</span><span class="p">()</span>
<span class="k">rescue</span> <span class="no">MeoBiBatCoc</span><span class="p">,</span> <span class="no">MeoBiDauChan</span> <span class="o">=&gt;</span> <span class="n">e</span>
  <span class="c1"># do something</span>
<span class="k">end</span></code></pre></td></tr></table>
</div>
</div>
<p>Đây là cách tốt nhất, ta goi trực tiếp đến trường hợp ngoại lệ mà ta cần bắt lấy và xử lý.</p>

<h2 id="kết-luận">Kết luận</h2>

<p>Nếu có phản hồi hãy để lại bình luận bên dưới bài viết.</p>

    </div>

    <div class="post-copyright">
  <p class="copyright-item">
    <span class="item-title">Author</span>
    <span class="item-content">Duy Chinh</span>
  </p>
  <p class="copyright-item">
    <span class="item-title">LastMod</span>
    <span class="item-content">
        2019-06-10
        
    </span>
  </p>
  
  
</div>
<footer class="post-footer">
      <div class="post-tags">
          <a href="/tags/rails/">rails</a>
          <a href="/tags/ruby/">ruby</a>
          </div>
      <nav class="post-nav">
        <a class="prev" href="/post/2019-06-11-public-private-va-protected-method-trong-ruby/">
            <i class="iconfont icon-left"></i>
            <span class="prev-text nav-default">Public, private và protected</span>
            <span class="prev-text nav-mobile">Prev</span>
          </a>
        <a class="next" href="/post/2019-06-09-luu-y-ngan-gon-ve-scope-va-class-method/">
            <span class="next-text nav-default">So sánh Class method và Scope</span>
            <span class="next-text nav-mobile">Next</span>
            <i class="iconfont icon-right"></i>
          </a>
      </nav>
    </footer>
  </article>
        </div>
        
  
  

  

      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
      <a href="mailto:hduychinh@gmail.com" class="iconfont icon-email" title="email"></a>
      <a href="https://facebook.com/hoangduychinh1995" class="iconfont icon-facebook" title="facebook"></a>
      <a href="https://www.linkedin.com/in/chinhhd308/" class="iconfont icon-linkedin" title="linkedin"></a>
  <a href="https://1312047.github.io/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    2018 - 
    2019
    <span class="heart">
      <i class="iconfont icon-heart"></i>
    </span>
    <span class="author">Duy Chinh</span>
  </span>
</div>
    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>
<script type="text/javascript" src="/dist/even.26188efa.min.js"></script>








</body>
</html>
